GET http://localhost:8080/timers/
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

###

POST http://localhost:8080/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

{
  "categoryName": "Senior Project",
  "color": "#0000FF"
}

###

POST http://localhost:8080/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

{
  "categoryName": "Sleep",
  "color": "#0000FF"
}

###

POST http://localhost:8080/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

{
  "categoryName": "Homework",
  "color": "#0000FF"
}

###

PUT http://localhost:8080/timer/646c344f73cd3ce246cf5616
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

{
  "categoryName": "Homework",
  "color": "#0000FF",
  "hoursLogged": 10,
  "minutesLogged": 10,
  "isRunning": false,
  "lastToggled": "2023-05-21T05:32:53.682Z"
}

###

PUT http://localhost:8080/timer/646c344f73cd3ce246cf5616
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE

{
"categoryName": "Homework",
"color": "#0000FF",
"hoursLogged": 0,
"minutesLogged": 0,
"isRunning": false,
"lastToggled": "2023-05-22T05:32:53.682Z"
}

###

DELETE http://localhost:8080/timer/647d6c4eae1f7f676bf22fec
Content-Type: application/json
Cookie: connect.sid=s%3At3LNKCuuw4ex9kaxiKJWAN7_5e0wtjhW.hfW6IP%2BeKBI5zFVcWAnsABFwT2U34VEmEXEC18mKlmE