GET https://time-tracker-591z.onrender.com/timers/
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

{
  "categoryName": "Senior Project",
  "color": "#0000FF"
}

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

{
  "categoryName": "Sleep",
  "color": "#0000FF"
}

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

{
  "categoryName": "Homework",
  "color": "#0000FF"
}

###

PUT https://time-tracker-591z.onrender.com/timer/648952cef20924429ffa2ce8
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

{
  "categoryName": "Homework",
  "color": "#0000FF",
  "hoursLogged": 10,
  "minutesLogged": 10,
  "isRunning": false,
  "lastToggled": "2023-05-21T05:32:53.682Z"
}

###

PUT https://time-tracker-591z.onrender.com/timer/648954b3ff1177a18084b945
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4

{
  "categoryName": "Homework",
  "color": "#0000FF",
  "hoursLogged": 0,
  "minutesLogged": 0,
  "isRunning": false,
  "lastToggled": "2023-05-22T05:32:53.682Z"
}

###

DELETE https://time-tracker-591z.onrender.com/timer/648954b3ff1177a18084b945
Content-Type: application/json
Cookie: connect.sid=s%3AnpGgT9ofe50h7rEhDSQk-GdDzcRLgHaW.%2B88ZIJNmMgJQf9uZKnwjSAiy1vbaFdz7mXS3T0uSJT4