GET https://time-tracker-591z.onrender.com/timers/
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

{
  "categoryName": "Senior Project",
  "color": "#0000FF"
}

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

{
  "categoryName": "Sleep",
  "color": "#0000FF"
}

###

POST https://time-tracker-591z.onrender.com/new-timer
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

{
  "categoryName": "Homework",
  "color": "#0000FF"
}

###

PUT https://time-tracker-591z.onrender.com/timer/64894f679655bdeb5b0d579b
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

{
  "categoryName": "Homework",
  "color": "#0000FF",
  "hoursLogged": 10,
  "minutesLogged": 10,
  "isRunning": false,
  "lastToggled": "2023-05-21T05:32:53.682Z"
}

###

PUT https://time-tracker-591z.onrender.com/timer/64894f679655bdeb5b0d579b
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8

{
  "categoryName": "Homework",
  "color": "#0000FF",
  "hoursLogged": 0,
  "minutesLogged": 0,
  "isRunning": false,
  "lastToggled": "2023-05-22T05:32:53.682Z"
}

###

DELETE https://time-tracker-591z.onrender.com/timer/64894f679655bdeb5b0d579b
Content-Type: application/json
Cookie: connect.sid=s%3AL5pXlaJzQjwLuZ8dOZICrtkFkp_5hJTk.NhJILCzVzHWC5ns72y4fuQp9wtI7cSNwWcV6dnjW%2F%2B8